### PR TITLE
Text changes + typos

### PR DESCRIPTION
**Pull request by MarionPlanque**

### CODE REVIEW

**Comment by fxi** [comment]
Thanks.
Nearly nailed it. As you also changed an id, I have to modify the code to reflect this before merging. So I can't merge now.

**Comment by MarionPlanque** [comment]
I see the problem; I need to ask for some help to delete the 'Change classe into theme + typo' suggestion, because it is the part where the problem is. I put this as a priority

**Comment by MarionPlanque** [comment]
My bad, I thought 'I can't merge now' meant that you were blocked and you couldn't do anything, meaning I had to do it.
Well noted, I don't touch anything

**Comment by fxi** [comment]
Yep, doing code stuff often implies to read things twice, to reduce the speed of your thoughts and to store a little bit more information in your short term memory than usual.

**Comment by MarionPlanque** [comment]
Ant I also required to have coding skills I guess

**Pull request merged**
